### ISSUE TITLE
Cambio Firma

### ISSUE THREAD

**Issue by markitosgv** [ssheduardo/sermepa#17]
Hola, como ya sabéis se está cambiando el método de firma de SHA1 a SHA256, por tanto esta librería quedará obsoleta para esa fecha si no realizamos el cambio.

Además se han realizado otros cambios, ahora por ejemplo el formulario tan sólo lleva 3 parámetros:

```php
<input type="text" name="Ds_SignatureVersion" value="<?php echo $version; ?>"/></br>
<input type="text" name="Ds_MerchantParameters" value="<?php echo $params; ?>"/></br>
<input type="text" name="Ds_Signature" value="<?php echo $signature; ?>"/></br>
```

- Ds_MerchantParameters:
   - Es un array de los parámetros: Necesitamos pasarlos a JSON y luego codificar en base64

- Ds_Signature
   - Se decodifica la clave proporcionada por el banco y se encripta junto con los parámetros anteriores;  por último todo se codifica en base64

- Ds_SignatureVersion
   - Especificaremos la versión de la firma: HMAC_SHA256_V1

La comprobación también cambiaría.

**Comment by ssheduardo** [comment]
Hola @markitosgv,
Hace días estuve hablando con otra persona que me aviso de este cambio, ya tengo la documentación y los ejemplos, como sabéis el código de ejemplo y su class Api ya viene todo lo necesario para poder trabajar desde el minuto cero.
Creo que tomaré como base dicha función (haciendo comentario de los derechos a quien pertenece claro esta) y reescribir la clase a este nuevo.

**Comment by markitosgv** [comment]
@ssheduardo perfecto, si necesitas una mano por aquí estamos. 

De todos modos... ¿cuando tenías pensado ponerte con ello? Tengo un par de sistemas que migrar y me gustaría probarlo.

**Comment by ssheduardo** [comment]
@markitosgv me iba a poner la semana pasada pero no tuve tiempo, este fin de semana ya me pongo a migrar y probar que también tengo algunos usuarios que tengo que migrar la clase.

**Comment by markitosgv** [comment]
perfecto @ssheduardo lo dicho cualquier cosa por aquí estamos

**Comment by facine** [comment]
Por si alguien le interesa o quiere ayudar a testear la migración a SHA256, yo he creé otra librería: https://github.com/CommerceRedsys/sermepa

**Comment by ssheduardo** [comment]
Ya acabo de subir una versión DEV en la rama Develop para realizar las pruebas correspondientes y feedback.
