### ISSUE TITLE
Cambio de Algorítmo SHA-1 a SHA-256

### ISSUE THREAD

**Issue by jmgarciamari** [ssheduardo/sermepa#19]
Hola, hoy me han comentado que los comercios que esten funcionando con el algoritmo SHA-1 dejaran de funcionar el día 23 de noviembre de este año, estoy utilizando esta librería pero veo que tiene el SHA-1.
Habría que sustituir la función
```php
sha1($string);
```
por
```php
hash( 'sha256', $string );
```
¿Sería correcto?

Gracias

[Migración a SHA-256](https://canales.redsys.es/canales/ayuda/migracionSHA256.html)

**Comment by ssheduardo** [comment]
Hola @jmgarciamari, no es solo cambiar el hash y ya hay más cosas por detrás, ta he preparado un versión DEV para las pruebas correspondientes hasta que este estable y pasemos a la versión estable.
https://github.com/ssheduardo/sermepa/tree/develop

**Comment by jmgarciamari** [comment]
Si, me he dado cuenta luego, lo siento, y muchas gracias por esta librería.
