### ISSUE TITLE
me falla a la hora de recibir los datos de vuelta...

### ISSUE THREAD

**Issue by jjdarias** [ssheduardo/sermepa#20]
Hola @ssheduardo , he estado probando la librería y todo funciona correctamente, sólo que a la hora de comprobar los datos devueltos, me falla en la llamada:  $pasarela->comprobar($_POST)
y es porque estoy viendo que los datos me vienen en $_GET
que vengan en POST o GET hay alguna forma de definirlo?
prefiero que me vengan en POST porque después me los pega detrás de la "url ok" en este caso...

Un saludo y gracias

**Comment by ssheduardo** [comment]
Hola @jjdarias  el método comprobrar recibe un POST (esto es cuando se activa la notificación online), por lo que veo es que estas recogiendo los datos de la url OK que va por GET, esto no es tan fiable para actualizar tus datos.
Te todas formas hay una nueva versión en pruebas ahora dado que el banco ha cambiado la forma de recibir los datos.  (https://github.com/ssheduardo/sermepa/tree/develop)

**Comment by jjdarias** [comment]
Ok, entonces lo que tendré es que activar la notificación online, lo miro en el panel, actualmente nunca me va a la url_notificacion, imagino que sea por no tenerlo activado.

Sí que he mirado incluso una API que tienen estos de Redsys: http://www.redsys.es/wps/portal/redsys/publica/areadeserviciosweb/descargaDeDocumentacionYEjecutables/!ut/p/a1/04_Sj9CPykssy0xPLMnMz0vMAfGjzOItHS1dDT3dDTz9g82MDDzD_HyNfPwdDfwDDIAKInErcHczJ06_AQ7gaEBIf7h-FFiJh7-zu6FRsIGXu7mTJVCfoZOTQbCPgYGRCVQBPieCFeBxQ0FuaIRBpqciAJbEr50!/dl5/d5/L2dBISEvZ0FBIS9nQSEh/ 
pero no me funciona con los datos que me ha pasado el BBVA, sin embargo con los datos que vienen de prueba en la API, funciona muy bien, que agregando lo que ya tienes en tu código de ejecutarRedireccion(), puede ser adaptado perfectamente. 

Y esta API de Redsys está bien porque también viene integrado el servicio de "uipay", sin tener que hacer nada más...

Muchas gracias y un saludo!

**Comment by ssheduardo** [comment]
Prueba la versión DEV  debería funcionar. (https://github.com/ssheduardo/sermepa/tree/develop)

**Comment by jjdarias** [comment]
Hola @ssheduardo , la acabo de probar y me da un error de javascript al llamar a la redirección:

"document.forms.redsys_form.submit is not a function"

y es por que el botón de submit se llama "submit" y no puede tener ese valor, aquí la explicación: http://stackoverflow.com/questions/833032/submit-is-not-a-function-error-in-javascript

Sólo con cambiar el nombre en
 $this->_setNameSubmit = 'submit';
 $this->_setIdSubmit = 'submit';

Listo!

No obstante debo de tener un problema en mi código FUC y terminal, asignados por el banco, ya que no me va a pagar con tarjeta y "uipay", me sale un error de Redsys, pero probé con los del ejemplo de la API y funciona OK, así que tu clase funciona correctamente! 

Gracias.

**Comment by ssheduardo** [comment]
Se ha cambiado los nombres por defecto para no tener este problema.
