### ISSUE TITLE
Recibir parametros en la notificación

### ISSUE THREAD

**Issue by markitosgv** [ssheduardo/sermepa#21]
Creo que sería útil tener un método para poder recoger los parámetros ya decodificados en la notificación.

Probablemente en el método check($key, $postData), se podrían guardar los parámetros decodificados y luego crear otro método para poder recoger el valor.

Es muy útil, por ejemplo, recoger el ID del pedido en la notificación para poder validarla.

**Comment by ssheduardo** [comment]
Hola @markitosgv, gracias a la colaboración de @popnoart, he agregado un nuevo método llamado getMerchantParameters, donde le pasamos el Ds_MerchantParameters y nos devuelve un array con los datos.
