### ISSUE TITLE
Erro al comprobar firma en notificación

### ISSUE THREAD

**Issue by markitosgv** [ssheduardo/sermepa#22]
Hola chicos,

Pues resulta que si cancelo la compra o me da algún error en el pago, llama a la notificación en el cual yo llamo al método check($key='', $postData), pues bien, siempre me devuelve 1 sea cual sea el caso, o sea que las firmas coinciden. A alguien más le pasa?

**Comment by eduk2** [comment]
Hola,

actualmente tengo disponibilidad baja y tardaré más de lo normal en responder.

Puedes esperar un poco más de lo normal a que te conteste o escribir a info@aquihaydominios.com para que te atienda cualquier otro compañero/a.

Si es algo técnico relacionado con dominios y alojamiento, puedes abrir un ticket desde tu zona privada: http://www.aquihaydominios.com/blog/como-abrir-un-ticket-a-nuestro-soporte-tecnico/

Recuerda también que si tienes contratado tiempo de servicios avanzados puedes abrir una tarea desde la herramienta de tareas para que te atienda cualquier otro compañero/a.

Gracias, un saludo.
________________________________

Eduardo Jiménez
E-mail: eduardo@aquihaydominios.com
Skype: aquihaydominios
http://www.aquihaydominios.com

**Comment by markitosgv** [comment]
Vale chicos, el tema es que al comprobar no sólo hay que mirar la firma sino también el código de respuesta.

```php
if ($this->tpv->check($key, $_POST) == 1 && $DsResponse == 0) {
//compra correcta
}
```

**Comment by ssheduardo** [comment]
Gracias por la aportación

**Comment by popnoart** [comment]
Buenas,

según los códigos de error que yo tengo, entre 0000 y 0099 la operación es correcta.

Los tenía guardados en un comentario por si algún día implementaba dar a los clientes pistas de qué había fallado:
Ds_Response:				
	0000 a 0099 => Transacción autorizada para pagos y preautorizaciones
	0900 => Transacción autorizada para devoluciones y confirmaciones
	101 => Tarjeta caducada
	102 => Tarjeta en excepción transitoria o bajo sospecha de fraude
	104/9104 => Operación no permitida para esa tarjeta o terminal
	116 => Disponible insuficiente
	118 => Tarjeta no registrada
	129 => Código de seguridad (CVV2/CVC2) incorrecto
	180 => Tarjeta ajena al servicio
	184 => Error en la autenticación del titular
	190 => Denegación sin especificar Motivo
	191 => Fecha de caducidad errónea
	202 => Tarjeta en excepción transitoria o bajo sospecha de fraude con retirada de tarjeta
	912/9912 => Emisor no disponible
	Cualquier otro valor => Transacción denegada

**Comment by ssheduardo** [comment]
@markitosgv , @popnoart me pasan sus email para coordinar mejoras si os parece.?

**Comment by markitosgv** [comment]
Está en mi perfil público Eduardo ;-)

**Comment by ssheduardo** [comment]
OK

**Comment by popnoart** [comment]
El mio lo he hecho público también!
