### ISSUE TITLE
Precio total (Amount) equivocado

### ISSUE THREAD

**Issue by jmgarciamari** [ssheduardo/sermepa#25]
Hola, he hecho una prueba de compra y yo le paso a la libreria un precio de 21,9 y cuando he ido a pagar me ponia 219€, puede ser que hayan modificado el tener que multiplicarlo por 100? Con la versión anterior me funcionaba bien

**Comment by luckyshot** [comment]
Tienes que poner el precio en decimales, es decir, 21,90 euros pon 2190.

**Comment by ssheduardo** [comment]
Efectivamente hay que poner '21,90', al parecer la función de conversión falla al poner '21,9'.
Voy a ver como solucionar ese bug o buscar otro.

**Comment by luckyshot** [comment]
(Si no recuerdo mal) es sin la coma (2190), la variable es un Integer.

**Comment by jmgarciamari** [comment]
había probado en vez de que se multiplicara por 100 he puesto por 10 y funciona, por eso digo si puede ser que hayan cambiado algo

**Comment by ssheduardo** [comment]
La función internamente debe enviar un entero en este caso si enviamos 21,90 ó 21.90 este le enviará a redsys 2190, así que deberías poner
```
$redsys->setAmount('21.90'); 
o
 $redsys->setAmount('21,90');
```

**Comment by ssheduardo** [comment]
Si ha quedado claro, cierro el issues

**Comment by jmgarciamari** [comment]
si, me faltaba que los precios se me quedaban tal que así: 22.9 en vez de 22.90

pasadole la funcion number_format($totalAmount, 2, ',', ' ')
Arreglado, muchas gracias
