### ISSUE TITLE
Url_Notification con parametros

### ISSUE THREAD

**Issue by jmgarciamari** [ssheduardo/sermepa#26]
Hola, con la libreria anterior tenia como urlNotification una web que pasandole el numero de pedido por GET marcaba como que habia pagado, pero ahora no funciona, si ejecuto la url funciona, pero parece ser que el TPV no accede a esa direccion.

**Comment by ssheduardo** [comment]
Hola @jmgarciamari no habrás issues para este tipo de pregunta, no son fallos.
La url de notificación va por POST nunca por GET, verifica los datos que recoges por POST para realizar las operaciones correspondientes, de todas formas en la página tienes un ejemplo de lo que devuelve.
Cierro el issue, para cualquier duda tengo ahí mi correo.

**Comment by jmgarciamari** [comment]
Ok, he estado probando para que me envie un correo con los datos $_POST que le llegan y me llega vacio, he hecho una prueba con el postman y me funciona bien. No encuentro tu correo

**Comment by ssheduardo** [comment]
Lo tienes en composer.json
