### ISSUE TITLE
Pago por referencia (Pago 1-Clic, sin autorización)

### ISSUE THREAD

**Issue by luckyshot** [ssheduardo/sermepa#29]
Desde el 11 Dic 2015 es posible el pago por referencia (sin autenticación) que permite realizar compras sin necesitar ninguna acción por parte del usuario (guardas un token en el servidor junto con la fecha de caducidad de la tarjeta).

Utiliza el nuevo campo `Ds_Merchant_DirectPayment` entre otros.

Hay planes de implementar esta funcionalidad? Alguien está trabajando en ello?

**Comment by ssheduardo** [comment]
Hola @luckyshot, 
No había visto esa opción, si quieres aportar documentación al respecto, podemos integrarlo o si en caso quieres hacerlo y enviar un pull request sin problemas.
