### ISSUE TITLE
Cómo extender _setParameters?

### ISSUE THREAD

**Issue by atrandafir** [ssheduardo/sermepa#30]
Creamos una clase en nuestra aplicación que extiende de la clase original de este repositorio.

Al crear métodos nuevos para que asignen otros _setParameters nos dimos cuenta que no los agrega al _setParameters original de la clase padre. 

Al parecer debido a que la propiedad está definida como private, cambiando a protected sí que lo permitió.

Aunque para realizar el cambio tuvimos que copiar la clase original dentro del código de la app para poder alterarla.

**Comment by ssheduardo** [comment]
Efectivamente, no pensé que iban a extender la clase, grave error.
Puedo cambiarlo sin problemas, pero lo último que comentas que tuviste que copiar el código dentro de la app me ha dejado en duda.
