### ISSUE TITLE
Problema con generateMerchantSignature($key)

### ISSUE THREAD

**Issue by puajklejos** [ssheduardo/sermepa#31]
Buenos dias,
Estaba haciendo una página web de compra y venta de fotos en localhost. Al tenerla acaba la he subido a un servidor, pero ahora mismo que esta en el servidor no me genera la signatura.
- En consola siempre me aparece el mismo error "Failed to load resource: the server responded with a status of 500 (Internal Server Error)". Me gustaria saber por que es.
Le doy la url de la página, si realiza todo el proceso cuando se encuentre en la pestaña de compra(Deberá rellenar los campos emails) verá que no me genera ninguna signatura y no me la posiciona en su lugar correcto. 
**URL: https://www.rider1000foto.com**
La plataforma esta en modo "Test", asi que no estoy haciendo publicidad.
Muchas gracias, 
Saludos

**Comment by ssheduardo** [comment]
Probablemente sea el servidor, dado que en localhost funciona sin problemas, pueda ser eso.
De todas formas la forma más sencilla es subir una página con el ejemplo que propongo y mira si falla o no, así puede descartar si el error es del servidor o código.

**Comment by puajklejos** [comment]
He estado mirando los registros que me aparecen en el servidor y me aparece este en concreto, creo que es el problema:
    private function encrypt_3DES($data, $key){
        $iv = "\0\0\0\0\0\0\0\0";
        $ciphertext = mcrypt_encrypt(MCRYPT_3DES, $key, $data, MCRYPT_MODE_CBC, $iv);
        return $ciphertext;
    }

**Comment by ssheduardo** [comment]
Mira que tu servidor tiene instalado mcrypt_encrypt

**Comment by puajklejos** [comment]
me falla en esa funcion.
En el registro de errores aparece lo siguiente:
mod_fcgid: stderr: PHP Fatal error: Call to undefined function mcrypt_encrypt() in /var/www/vhosts/rider1000foto.com/httpdocs/tienda/Tpv.php on line 558

**Comment by puajklejos** [comment]
Como lo puedo instalar?

**Comment by ssheduardo** [comment]
Si tienes acceso root al servidor lo instalas, en internet hay infinidad de tutoriales super sencillos.
En caso contrario tendrías que hablar con tu proveedor de hosting para que lo instalen

**Comment by ssheduardo** [comment]
Si esta resuelto, cierro esto.

**Comment by hmorv** [comment]
Buenas,

Prueba con `apt-get install php5-mcrypt`

**Comment by puajklejos** [comment]
Esta resuleto, puedes cerrarlo. Muchas gracias.

**Comment by ssheduardo** [comment]
Genial
