### ISSUE TITLE
Recuperar información de la compra

### ISSUE THREAD

**Issue by itwoorks** [ssheduardo/sermepa#33]
Primero de todo darte las gracias por este código.
He implementado tu código y me lleva correctamente al banco para realizar el pago y luego me devuelve a la página indicada en la variable $setUrlOk, el problema es que no consigo recuperar los datos de la transacción en la página indicada en $setUrlOk.

Este es el código que añado a la pagina definida en $setUrlOk:
```
	include_once('public/assets/sermepa/src/Sermepa/Tpv/Tpv.php'); 
	$redsys->getMerchantParameters($_POST["Ds_MerchantParameters"]);
```
Y este el error que me aparece: Undefined variable: redsys.
Que estoy haciendo mal? Gracias por adelantado y un saludo,

**Comment by ssheduardo** [comment]
Puedes agregar el resto de código?

**Comment by itwoorks** [comment]
Este es el codigo en pagina confirmacion.php:
<? try{
    $key = 'sq7HjrUOBfKmC576ILgskD5srU870gJ7';

    $redsys = new Sermepa\Tpv\Tpv();
    $redsys->setAmount($_POST["importe"]);
    $redsys->setOrder(time());
    $redsys->setMerchantcode('327234688'); //Reemplazar por el código que proporciona el banco
    $redsys->setCurrency('978');
    $redsys->setTransactiontype('0');
    $redsys->setTerminal('1');
    $redsys->setMethod('C'); //Solo pago con tarjeta, no mostramos iupay
    $redsys->setNotification('http://localhost/noti.php'); //Url de notificacion
    $redsys->setUrlOk('http://www.ferrerysaret.com/es/privada/gracias'); //Url OK 
    $redsys->setUrlKo('http://www.ferrerysaret.com/es/privada/fallo'); //Url KO
    $redsys->setVersion('HMAC_SHA256_V1');
    $redsys->setTradeName('Ferrer y Saret');
    $redsys->setTitular('Ferrer y Saret');
    $redsys->setProductDescription('Lista de boda online');
    $redsys->setEnviroment('test'); //Entorno test

    $signature = $redsys->generateMerchantSignature($key);
    $redsys->setMerchantSignature($signature);

    $form = $redsys->createForm();
}
catch(Exception $e){
    echo $e->getMessage();
}
echo $form; ?>

Al apretar submit vamos a la pagina del banco y realizamos el pago.
Al hacer click on volver vamos a la pagina http://www.ferrerysaret.com/es/privada/gracias
En esta el codigo es:

	include_once('public/assets/sermepa/src/Sermepa/Tpv/Tpv.php'); 
	$redsys->getMerchantParameters($_POST["Ds_MerchantParameters"]);

Que me estoy dejando?

**Comment by ssheduardo** [comment]
Te falta instanciar redsys
```
include_once('public/assets/sermepa/src/Sermepa/Tpv/Tpv.php'); 
$redsys = new Sermepa\Tpv\Tpv();
$redsys->getMerchantParameters($_POST["Ds_MerchantParameters"]);
```

**Comment by itwoorks** [comment]
Buenas,
He añadido la incialización pero me sigue apareciendo el error: 
Undefined index: Ds_MerchantParameters

Puedo ver en la url que el parametro Ds_MerchantParameters existe, pero luego me dice undefined...

**Comment by ssheduardo** [comment]
Una cosa esta mal implementado por así decirlo, si vas a recuperar los datos es través de la url de notificación:
```
$redsys->setNotification('http://localhost/noti.php'); //Url de notificacion
```

**Comment by itwoorks** [comment]
Entonces entiendo que el fallo es que a la Url de setUrlOk no recibe los datos de la compra y por eso no puede mostrarlos y dice undefined? 
Entonces como lo hago para mandarlo a la url de setNotification y así poder tratar los datos? O esto no se hace así?
Basicamente lo que quiero es que si todo ha funcionado ok guardarlo en la base de datos y mandarle un email.

Muchísimas gracias por tu ayuda,

**Comment by itwoorks** [comment]
Estoy pensando que si vamos hasta la pagina definida en setUrlOk significa que todo ha ido bien y entonces puedo mandar el email, la información puedo recuperarla si la guardo en variables Session verdad?

**Comment by ssheduardo** [comment]
Debes diferenciar 2 cosas:
1. La url de OK es solo para decir Ok, su compra se ha realizado correctamente y poco más.
2. La url de notificación es la encargada de guardar en bbdd, enviar email, etc, dado que es una url que el usuario no tendrá acceso.

**Comment by itwoorks** [comment]
Ok, entonces entiendo que el código php que ponga en la url de notificación se ejecutará aunque el usuario no vaya a esa dirección?
De nuevo muchísimas gracias por tu tiempo.

**Comment by ssheduardo** [comment]
Así es, ese llamado lo hace el banco, no te preocupes

**Comment by itwoorks** [comment]
Ok, voy a pelearme a ver si lo consigo.

**Comment by itwoorks** [comment]
Veo que el código de la vista notificaciones se ejecuta como me has indicado.
Muchísimas gracias por tu ayuda y tu tiempo.
Cierro el hilo y te dejo tranquilo. ; )
