### ISSUE TITLE
Ds_Merchant_PartialPayment

### ISSUE THREAD

**Issue by jjdarias** [ssheduardo/sermepa#34]
Hola, buen día,
tengo la necesidad de hacer una integración de tu librería con pagos fraccionados, en mi caso en el BBVA. Y me han dicho desde el banco que hay que incorporar el campo  "Ds_Merchant_PartialPayment" donde se envían los plazos de financiación siempre y cuando no sea un pago al contado.

Imagino que sea tan sencillo como hacer un nuevo método que agregue un item más a Parameters, tal como así:  $this->_setParameters['DS_MERCHANT_PARTIALPAYMENT'] = '03' (3 meses sin intereses). El valor por defecto es '02' : Pago con tarjeta al contado.

Pero quería confirmarlo contigo y el resto de la comunidad. Qué me dices?

Los códigos que tengo hasta ahora y me falta probar/validar son:
![image](https://cloud.githubusercontent.com/assets/15450816/15887173/10b348dc-2d61-11e6-898e-3766218a8baf.png)

**Comment by ssheduardo** [comment]
No he tenido la oportunidad de realizar un pago a plazos, tocará investigar para implementarlo.
Si tienes más info para ver y probar.

**Comment by ssheduardo** [comment]
@jjdarias he buscado información al respecto y no he encontrado casi nada, he implementado dicho parámetro en una versión de pruebas y no va, contacta con el banco por si tienen alguna prueba, comentarle a los del banco si dicha operativa esta habilitada para la versión actual.

**Comment by jjdarias** [comment]
Nada, me han dicho desde el banco que el tema del pago fraccionado hay que hacerlo desde el webservice. Saludos

**Comment by ssheduardo** [comment]
Vaya, no he tocado el tema de webservices en esta clase.
