### ISSUE TITLE
get para ciertos parametros

### ISSUE THREAD

**Issue by keopx** [ssheduardo/sermepa#37]
Estoy usando este componente, pero veo que no dispone de algunos métodos.

Como uso Drupal, quiero usar mi propio sistema form (el de drupal), pero hay un par de métodos que hecho de menos.

- getVersion()
- getSignature()

De esta manera podría usar el objeto TPV sin tener que estar manteniendo variables locales.

**Comment by ssheduardo** [comment]
Hola @keopx a ver si entiendo tu requerimiento.
Necesitas:
- getVersion devolvería:  **HMAC_SHA256_V1** ?
- getMerchantSignature devolvería:  **$this->_setSignature** ?

**Comment by keopx** [comment]
Si, eso es.

Entiendo que si existen métodos privados, debería de tener sus setters y sus getters.

Al tener el metdodo createForm() no los necesitas, pero en el caso que estoy implementetando seria genia poder recuperar esos valores.

**Comment by ssheduardo** [comment]
Ok, a lo largo del día lo implemento.

**Comment by keopx** [comment]
Muchas gracias :+1:

**Comment by ssheduardo** [comment]
Vale, esta casi listo.
Por recapitular un poco quedaría así:
```
....
....
 $redsys->setMerchantSignature($signature);
 echo "Version: {$redsys->getVersion()} <br/>";
 echo "MerchantSignature: {$redsys->getMerchantSignature()} <br/>";
....
....
```

> Lógicamente obtendrás el signature luego de asignarlo

**Comment by keopx** [comment]
Genial!

**Comment by keopx** [comment]
Funciona genial, muchas gracias :)

**Comment by keopx** [comment]
Funciona genial, muchas gracias :)
