### ISSUE TITLE
No puedo comprobar el pago

### ISSUE THREAD

**Issue by pqrs** [ssheduardo/sermepa#40]
Hola, ¿podéis por favor confirmar que las notificaciones de pago siguen funcionando como hasta ahora?

Llevo un día loco, a la url especificada en _$redsys->setNotification_ no accede redsys nunca pese a dar el ok a la transacción. Hace unos meses hice unas pruebas y me funcionó todo correctamente. Ahora, ese mismo código, sin ninguna modificación, funciona correctamente excepto la notificación. ¿A alguien más le pasa? 

Muchas gracias.

**Comment by ssheduardo** [comment]
Si esta funcionando, lo acabo de probar ahora
```
Array
(
    [Ds_Date] => 18/10/2016
    [Ds_Hour] => 11:01
    [Ds_SecurePayment] => 1
    [Ds_Card_Number] => 454881******0004
    [Ds_Card_Country] => 724
    [Ds_Amount] => 22500
    [Ds_Currency] => 978
    [Ds_Order] => 1476781234
    [Ds_MerchantCode] => 999008881
    [Ds_Terminal] => 001
    [Ds_Response] => 0000
    [Ds_MerchantData] => xxxxxx_10_64455_Descripcion_del_pedido
    [Ds_TransactionType] => 0
    [Ds_ConsumerLanguage] => 1
    [Ds_AuthorisationCode] => 357964
)
```

**Comment by pqrs** [comment]
Muchas gracias @ssheduardo, evidentemente el fallo tiene que estar en mi código entonces, aunque no me explico dónde, sobre todo porque como te decía funcionaba perfectamente. Le doy una vuelta luego y ya comento.

**Comment by ssheduardo** [comment]
Perfecto, a la espera para ver donde estaba el error.

**Comment by pqrs** [comment]
Hola de nuevo, ayer no pude dedicarle tiempo a esto. La cuestión es que esta mañana he ido a probarlo y antes de tocar nada lo he ejecutado y ha vuelto a funcionar sin problema, tanto el código que inicialmente empezó a fallarme y que funcionaba hace unos meses (está en una página de Drupal, generando un nodo nuevo "pago" por cada notificación recibida), como el código que anteayer copié y pegué de tus ejemplos.

No entiendo nada :/

En todo caso, gracias de nuevo @ssheduardo por haber contestado tan rápido y disculpa que abriera un issue por esta tontería, fuera lo que fuese.

**Comment by ssheduardo** [comment]
De nada
