### ISSUE TITLE
Como enviar los datos.

### ISSUE THREAD

**Issue by MarcosAguayo** [ssheduardo/sermepa#48]
No consigo encontrar como enviar los datos generados con la clase al webservice de Redsys. Podrías ayudarme? No encuentro en que función envias los datos.

Gracias

**Comment by ssheduardo** [comment]
Hola @MarcosAguayo , la clase no tiene dicha opción, lo que hace directamente es generar el botón para que el usuario pueda darle click y luego ser llevado a la web del banco o puedes generar el botón y ocultarlo con css y lanzarlo con javascript para que nada más entrar a dicha página se lance el proceso automáticamente.

**Comment by MarcosAguayo** [comment]
Muchas gracias por la respuesta. Entonces entiendo que no funciona sin redirección y no se puede usar el webservice para hacerlo todo en tu página no? Conoces alguna forma de hacer esto? Alguna libreria o clase?

**Comment by ssheduardo** [comment]
Exactamente que quieres hacer?

**Comment by MarcosAguayo** [comment]
He encontrado esto: https://github.com/MarcosAguayo/Redsys que creo que sirve
Gracias de todas formas por responder tan rápido.

**Comment by ssheduardo** [comment]
Anda, revisando el código veo que ha usado mi clase base para hacer la suya, esta bien.

**Comment by MarcosAguayo** [comment]
Si, cuando me ponga con ello lo mejoro, te hago un commit y si te interesa que esté en el repositorio  lo añades aquí, creo que está bien tener las dos opciones de integración.

**Comment by ssheduardo** [comment]
@MarcosAguayo genial, a la espera de tu pull request para integrar mejoras.
Gracias
