### ISSUE TITLE
Duda 

### ISSUE THREAD

**Issue by davidoween** [ssheduardo/sermepa#49]
Buenas, gracias por el código. Mi pregunta quizás sea un poco estúpida, es la siguiente:

Una vez configurado los distintos parámetros, en función de estos iré a un link u otro, verdad, y también en función de estos datos, la página tendrá un estilo u otro, no? De que TVP se supone que es la configuración del ejemplo?

El estilo tampoco se puede cambiar, no? 

Gracias por el aporte

**Comment by ssheduardo** [comment]
Hola,
Esta pasarela es para Redsys (Banco Santander, Sabadell, etc, etc).
Tienes dos entornos uno de prueba y otro en real,
Lo que hace realmente es crear un simple botón para darle a pagar, puedes
agregar estilos al boton.


*Eduardo D. | Web Developer*

<https://twitter.com/eduardo_dx>  <http://es.linkedin.com/in/eduardodx/>
<https://github.com/ssheduardo/>

**Comment by davidoween** [comment]
Pero mi pregunta no es esa. Mi pregunta es que dependiendo del banco que te
proporcione el TPV la página desde la cual pones los datos para pagar será
distinta, o estoy equivocado y siempre será la que viene en el ejemplo?

**Comment by ssheduardo** [comment]
Ahhh, eso lo proporciona el banco, tendrías que hablar con ellos.


*Eduardo D. | Web Developer*

<https://twitter.com/eduardo_dx>  <http://es.linkedin.com/in/eduardodx/>
<https://github.com/ssheduardo/>
