### ISSUE TITLE
Problema con la MERCHANTURL

### ISSUE THREAD

**Issue by DavidSis** [ssheduardo/sermepa#51]
Buenas, estoy probando tu clase para una tienda virtual que estoy montando y me encuentro con un problemilla. El pago lo realiza bien, pero cuando salgo de redsys e intento guardar los datos del pago me salta directamente a la URLOK sin pasar por la MERCHANTURL. He probado ya mil cosas y no se si el fallo esta en mi codigo o en la plataforma de pago. Muchas gracias por tu tiempo.

**Comment by ssheduardo** [comment]
Hola,
Recuerda que redsys te envía los datos de la transacción a la url de notificación que le has indicado.

**Comment by Kyosfonica** [comment]
Yo uso la librería para un TPV virtual de Banco Sabadell y tanto URLKO, URLOK como MERCHANTURL envían la misma información. MERCHANTURL es la llamada del TPV a tu servidor sin intervención del usuario, por si quieres hacer cosas en segundo plano sin ralentizar la experiencia del usuario.
No estás obligado a usarla ya que no es obligatoria y puedes perfectamente usar en su lugar solo URLKO y URLOK para gestionar los pagos que hayas recibido del TPV.

**Comment by DavidSis** [comment]
En teoria deberia pasar por la web que le marco en la url de notificacion, pero no pasa por ella, va directamente a URLOK, y esta no me vale porque ya no llegan los datos del pago (solo los de la sesion que he guardado antes). Muchas gracias por vuestras respuestas.

**Comment by angelphp** [comment]
Por la URL de las notificaciones no "pasa" antes del URL_OK. La notificación que te envia el banco es un POST con un JSON con todos los datos de la transacción. Esta puede ser inmediata o no. Como bien dice Kyosfonica no pasas primero por una y despues por la otra. 
Nosotros hemos tenido demoras de minutos (black friday 2016) para recibir la notificación, aunque normalmente es inmediato. 
Son URLs independientes, puedes pasarle o no la URL de notificación.

**Comment by DavidSis** [comment]
Pensaba que si, fallo mio, el caso es que en la URLOK no me llega ningun tipo de dato (ni por Get ni por POST) por eso pensaba que iba primero a una y luego a otra. Me sigue quedando la duda de porque no me llegan los datos al URLOK.

**Comment by ssheduardo** [comment]
Que raro el ok siempre devuelve algo y lo acabo de probar.

**Comment by DavidSis** [comment]
Vale, solucionado, es problema del TPV que no nos devuelve los valores (he probado con otro y en el URLOK ya nos llegan los valores). Muchas gracias por todo y me tocara discutir con los del TPV.

**Comment by ssheduardo** [comment]
De nada, cerramos issue.
