### ISSUE TITLE
recurring transaction

### ISSUE THREAD

**Issue by olegatro** [ssheduardo/sermepa#54]
Hi, we need add other merchant data than you described such as:
* `DS_MERCHANT_DATEFRECUENCY`
* `DS_MERCHANT_CHARGEEXPIRYDATE`
* `DS_MERCHANT_SUMTOTAL`
and for second transaction `DS_MERCHANT_AUTHORISATIONCODE` 

Perhaps, it would be more convenient if you added a method, for example, `setParameter` ?
Where we can set any parameter

**Comment by ssheduardo** [comment]
I understand, the next version can add the new parameters but you can make a fork and add the parameters.

**Comment by olegatro** [comment]
ok, thanks)

**Comment by vanandmkrtchyan** [comment]
Hi @ssheduardo. Humanity still needs this setters please add them to Tpv.

- DS_MERCHANT_DATEFRECUENCY
- DS_MERCHANT_CHARGEEXPIRYDATE
- DS_MERCHANT_SUMTOTAL

**Comment by ssheduardo** [comment]
Sorry, I forget add this values
I will add this tomorrow

**Comment by ssheduardo** [comment]
Added new methods for recurring payment
https://github.com/ssheduardo/sermepa/blob/master/CHANGELOG.md

**Comment by gsabater** [comment]
Hello @ssheduardo and @vanandmkrtchyan,

I'm trying to use this new methods for recurring payments.
Setting the parameters as this example, creates a new recurring payment on the bank, but only the first recurrent payment is processed.

```
  "DS_MERCHANT_TRANSACTIONTYPE" => "5"
  "DS_MERCHANT_SUMTOTAL" => 35000
  "DS_MERCHANT_CHARGEEXPIRYDATE" => "2020-02-10"
  "DS_MERCHANT_DATEFRECUENCY" => 1
```

I have contacted the bank and they told me that this implementation is obsolete. Have you guys managed to make it work? And, do you have any examples of how to achieve monthly payments?

Muchas gracias por el trabajo

**Comment by olegatro** [comment]
@gsabater  as I remember, for second recurring transaction you need `DS_MERCHANT_AUTHORISATIONCODE` which as I understand not implemented. 

We do not use spain banks right now, and migrated to stripe.

**Comment by olegatro** [comment]
@gsabater I agree with you, examples would be nice.

**Comment by olegatro** [comment]
reopened issue)

**Comment by ssheduardo** [comment]
Agregado method setParameters.

**Comment by phstc** [comment]
Have you guys managed to create an example for recurring payments?

**Comment by ssheduardo** [comment]
> Have you guys managed to create an example for recurring payments?

Hi,
Only I have this example. :(
