### ISSUE TITLE
TPV class not found

### ISSUE THREAD

**Issue by amirgee007** [ssheduardo/sermepa#55]
hi sir,
I just want to ask that how can I confirm payment is successful or not.

I am using this class but it returns me this error.

 $redsys = new Sermepa\Tpv\Tpv();

TPV class not found.
even that i have already installed in my laravel application.

**Comment by ssheduardo** [comment]
Hi @amirgee007,
Please paste the code for see the error.

**Comment by ssheduardo** [comment]
Sigues teniendo el mismo error?
