### ISSUE TITLE
Question: Redsys ya no devuelve el Ds_Card_Number??

### ISSUE THREAD

**Issue by jolugarbe** [ssheduardo/sermepa#57]
Buenas,
Antes que nada muchísimas gracias por esta aportación!

Estoy implementándolo en modo test y en los datos que me devuelve el pago no aparece el Ds_Card_Number para poder almacenar los últimos 4 dígitos de la tarjeta.

Recibo los siguientes datos en el array. ¿Hay algún método para obtenerlo o es Redsys quién ha dejado de retornarlo?

Ds_Terminal:001;
Ds_Response:0000;
Ds_Amount:300;
Ds_SecurePayment:1;
Ds_Card_Country:724;
Ds_Card_Brand:1;
Ds_ConsumerLanguage:1;
Ds_Date:22/05/2018;
Ds_Merchant_Identifier:42e3397351e5df1512b24e5d5cbcb464e4baaa89;
Ds_ExpiryDate:2012;
Ds_Order:000000000047;
Ds_MerchantCode:344473699;
Ds_TransactionType:0;
Ds_Hour:13:46;
Ds_AuthorisationCode:178541;
Ds_Currency:978;

Un saludo y muchas gracias.

**Comment by ssheduardo** [comment]
He estado buscando en los manuales que tengo y no he visto ese dato, si puedes contactar con el banco para que te confirmen si devuelven dicho parámetro.


Saludos

**Comment by jolugarbe** [comment]
Lo comentaba porque en tu descripción indicas que en la notificación debe llegar este array:

**Comment by jolugarbe** [comment]
//En la url de notificación nos devolverá algo como esto
Array
(
    [Ds_Date] => 20/10/2016
    [Ds_Hour] => 13:06
    [Ds_SecurePayment] => 1
    **[Ds_Card_Number] => 454881******0004**
    
    [Ds_ExpiryDate] => 2012
    [Ds_Merchant_Identifier] => cd8e4017c4c2f16bc9ccff87b0d07ad9c6cbd257

    [Ds_Card_Country] => 724
    [Ds_Amount] => 47700
    [Ds_Currency] => 978
    [Ds_Order] => 1476961526
    [Ds_MerchantCode] => 999008881
    [Ds_Terminal] => 001
    [Ds_Response] => 0000
    [Ds_MerchantData] => Descripcion_del_pedido_extra
    [Ds_TransactionType] => 0
    [Ds_ConsumerLanguage] => 1
    [Ds_AuthorisationCode] => 024772
)
