### ISSUE TITLE
setParameters como protected

### ISSUE THREAD

**Issue by alexanderttalvarez** [ssheduardo/sermepa#60]
Hola,

Estoy usando tu librería, que me parecer super útil, pero me he encontrado con un problemilla. Estoy intentando extenderla, porque necesito hacer pagos recurrentes y de momento no están contemplados en tu librería. Al intentar extenderla he querido acceder a **setParameters** desde mi nueva clase, pero al ser private pues claro, error al canto jajaja.

Sería interesante que pusieras setParameters como protected, o añadieras un método público para editarlo.

¡Gracias!

**Comment by ssheduardo** [comment]
Hola, he estado fuera por vacaciones, creo que con ponerlo en **protected** no afectaría al resto que esta usando la clase.
De todas maneras voy a estudiar las dos soluciones.

**Comment by ssheduardo** [comment]
Hola,
Estoy trabajando en una nueva actualización, cambiando los private por protected para facilitar el trabajo cuando quieran extender de la clase.

**Comment by alexanderttalvarez** [comment]
Buenos días,
Muchas gracias, creo que será algo muy útil para muchos y de fácil implementación.
Un saludo.

**Comment by ssheduardo** [comment]
Si, ya lo tenemos habilitado en la versión 1.2.7

**Comment by metelidrissi** [comment]
Hola @alexanderttalvarez 

¿Pudiste implementar la librería para hacer cobros recurrentes?

Un saludo
