### ISSUE TITLE
Question: ¿Es posible hacer pre autorizaciones sin acciones del usuario?

### ISSUE THREAD

**Issue by salbatore** [ssheduardo/sermepa#61]
Buenas Eduardo,

Antes de nada, darte mis felicitaciones por la claridad de tu código y ayudarnos a todos en integrar la pasarela.

Estoy haciendo pruebas con las preautorizaciones, ya he conseguido que la pasarela no haga uso de 3d secure hablando con el banco.

La duda que nadie me aclara es:

Existe alguna tarjeta o alguna situación en que la preautorización exija hacer uso de una pantalla maquetada por Redsys?

Sé que la pregunta es muy difusa. Estoy integrando tu código junto a una app nativa ios y no sé si es mala idea. No sé si es mejor hacerlo con un iframe por si existe alguna situación en que se exija completar un dato extra en una pantalla de Redsys.

Es decir, con tu código y una pasarela configurada con webservice y sin 3d secure... se requiere de alguna acción del usuario?

Gracias por tu ayuda

**Comment by ssheduardo** [comment]
Hola,
Llegaste a resolver esta duda?

**Comment by ssheduardo** [comment]
Dado que no hay respuesta, paso a cerrar esta pregunta
