### ISSUE TITLE
IUPAY

### ISSUE THREAD

**Issue by Cristoto** [ssheduardo/sermepa#62]
¿Cómo puedo mostrar el IUPAY?
¿Si no, lo tiene se le puede agregar?

**Comment by ssheduardo** [comment]
Hola,
Últimamente no he visto activa dicha opción que antes si estaba.
Voy a probarlo ahora que tenga un hueco.

**Comment by ssheduardo** [comment]
Al no obtener respuesta de @Cristoto cierre este ticket
