### ISSUE TITLE
Alguien tiene problemas con la tarjeta de pruebas autorizada?

### ISSUE THREAD

**Issue by popnoart** [ssheduardo/sermepa#63]
Buenas,

estoy teniendo problemas para realizar pruebas, y creo que el problema viene de la tarjeta autorizada. Me salta siempre este mensaje sin llegar a pasar por la petición de la clave del banco (el CIP):

> No se puede realizar la operación 
> La comunicación con el comercio no es posible en estos momentos. Por favor, inténtelo más tarde.
> 

Probando con la denegada me salta este mensaje:

> No se puede realizar la operación 
> Tarjeta ajena al servicio. (SIS0093)

No recuerdo de otras veces si esto es lo que debe salir, pero parece correcto.

En todo caso me funciona bien las urls de notificación, ok y ko.
He probado también con el ejemplo de "Enviar datos de la tarjeta" y mismo mensaje.

Las tarjetas que uso son:
Nº Tarjeta Autorizada: 4548812049400004
Fecha cad: 12/20
cvv: 123
CIP: 123456

Nº Tarjeta Denegada: 1111111111111117
Fecha cad: 12/20

A alguien le pasa?

**Comment by ssheduardo** [comment]
Hola,
Acabo de ver tu mensaje y efectivamente esta fallando, yo lo tenía montado en mi server con muchos ejemplos y todos fallan.

**Comment by popnoart** [comment]
Pues ya sabiendo que no es cosa mía intentaré contactar con ellos a ver qué dicen y ya os lo cuento. Gracias!

**Comment by ssheduardo** [comment]
Genial, estamos a la espera :D

**Comment by popnoart** [comment]
NIvel soporte técnico Redsys:

> Le informamos que para realizar pruebas en el entorno de REAL use una tarjeta propia REAL, no la que le facilitamos para realizar pruebas en TEST.
> 
> Si quiere realizar pruebas en TEST primero debe cambiar la clave de encriptación por la de TEST que te facilitamos en el mail de bienvenida y que su URL apunte a Sys-t no a Sys como apunta en entorno REAL, si no hace eso no podrá realizar pruebas en TEST de nuevo.
> 

No se ni para que me molesto, viendo el nivel que exhibieron cuando nos cambiaron a todos a este tpv...

**Comment by popnoart** [comment]
Bueno pues después de varios emails no he conseguido que lo arreglen, aunque si una solución parcial.
Si estabais cuando el lío de cambio de varias tpvs a redsys os acordareis que dijeron que los datos para el entorno test iban a ser específicos para cada cliente, pero que luego vimos que no era así y podíamos seguir usando los genéricos, bueno, pues parece que al final han cerrado el grifo y han aplicado la restricción. 
Me han dicho por activa y por pasiva que sí o sí tengo que usar el FUC específico del cliente y que el genérico no vale. Por mucho que les he insistido que ese fuc es el que aparece en el manual, nada, que use el del cliente.  Lo he hecho y efectivamente la tarjeta de prueba ha funcionado.

Así que adiós a hacer pruebas si no tienes un cliente que te facilite los datos.

**Comment by ssheduardo** [comment]
Vaya que pena, no tiene sentido habilitarlo sin tener un fuc del cliente final.
En fin, toca poner en las pruebas el FUC del cliente y listo.
A ver si actualizo el README, muchas gracias @popnoart

**Comment by popnoart** [comment]
Parece que no han terminado los problemas: ahora $signature y $signatureReceived no son iguales.

**Comment by ssheduardo** [comment]
Tantos cambios, eso te lo han confirmado??
Si es así en Real estará dando mucho fallos

**Comment by popnoart** [comment]
No, no, me refiero a que en entorno test, ahora que ya me funciona la tarjeta, he seguido con las pruebas. En la notificación es donde proceso internamente si han pagado y demás y me estaba volviendo loca porque no había manera, no me daba el pedido como pagado. Pensaba que era el Ds_Response  pero al separar esta parte 
`if ($redsys->check($key, $_POST) && $Ds_Response <= 99) {`
vi que no pasaba del 
`if ($redsys->check($key, $_POST)) {`

El caso es que creo que los fallos solo se producen en el entorno test. A ver si puedo probar en real.

**Comment by popnoart** [comment]
Bueno, misterio resuelto, ya he encontrado lo que me fallaba. Resulta que mis pedidos llevan un símbolo y al venir de vuelta venían codificados y la clave no coincidía claro :-D
Un urlencode después funcionaba perfectamente!

**Comment by popnoart** [comment]
Sí, eso parece, solo el cambio del FUC.
