### ISSUE TITLE
Contratar programador en Laravel y sistemas de pago

### ISSUE THREAD

**Issue by tpvvirtual** [ssheduardo/sermepa#67]
Hola Edudardo

Buenos días

He visto que has creado este plugin https://github.com/ssheduardo/sermepa#pago-con-referencia estoy buscando un programador que tenga experiencia en Laravel y sistemas de pago
Con pasarelas de pago de bancos españoles ¿podrías ayudarme?

Espero sus comentarios

Un saludo

**Comment by ssheduardo** [comment]
Hola muy buenas,
Dejame tu correo y hablamos.

**Comment by tpvvirtual** [comment]
Mi correo es info@tpvvirtual.net

Gracias

Enviado desde mi iPhone
