### ISSUE TITLE
No envía datos a la url de notificación

### ISSUE THREAD

**Issue by olimpiu6** [ssheduardo/sermepa#68]
Hola. Gracias por esta maravillosa clase. El problema que encontré usando el codigo de nuestra es que la url de notificación no recibe datos. Intento leer lo que entra en php://input y no hay nada. Tampoco entra nada en el POST del código de muestra. Estoy muy atascado.

**Comment by ssheduardo** [comment]
Es muy raro, mucha gente lo esta usando con el ejemplo y todo y ha podido obtener los datos, recuerda que la url de notificación, no puede ser tu **localhost**, tiene que ser una url que pueda acceder el banco de forma externa.

**Comment by olimpiu6** [comment]
Gracias por tu respuesta. La url no es localhost. Todo funciona, los pago, la re-dirección a las url  OK y KO solo las notificaciones no. Dejo el código:
<?php
$r =file_get_contents('php://input');
 file_put_contents(dirname(__FILE__) . '/noti.txt', $r . date('d-m-Y m:i:s'). ' - ', FILE_APPEND);

include_once('vendor/autoload.php');
  try{
    $redsys = new Sermepa\Tpv\Tpv();
    $key = '***************************';
   

    $parameters = $redsys->getMerchantParameters($_POST["Ds_MerchantParameters"]);
    $DsResponse = $parameters["Ds_Response"];
    $DsResponse += 0;
    if ($redsys->check($key, $_POST) && $DsResponse <= 99) {
        //acciones a realizar si es correcto, por ejemplo validar una reserva, mandar un mail de OK, guardar en bbdd o contactar con mensajería para preparar un pedido
        file_put_contents(dirname(__FILE__) . '/noti.txt', $DsResponse . "\r\n", FILE_APPEND);
    } else {
        //acciones a realizar si ha sido erroneo
        file_put_contents(dirname(__FILE__) . '/noti.txt', 'PAGO MAL ' . date('d-m-Y m:i:s') . "\r\n", FILE_APPEND);
    }
} catch (\Sermepa\Tpv\TpvException $e) {
    echo $e->getMessage();
}
?>

Gracias.

**Comment by olimpiu6** [comment]
<?php
$r =file_get_contents('php://input');
 file_put_contents(dirname(__FILE__) . '/noti.txt', $r . date('d-m-Y m:i:s'). ' - ', FILE_APPEND);

include_once('vendor/autoload.php');
  try{
    $redsys = new Sermepa\Tpv\Tpv();
    $key = '***************************';
   

    $parameters = $redsys->getMerchantParameters($_POST["Ds_MerchantParameters"]);
    $DsResponse = $parameters["Ds_Response"];
    $DsResponse += 0;
    if ($redsys->check($key, $_POST) && $DsResponse <= 99) {
        //acciones a realizar si es correcto, por ejemplo validar una reserva, mandar un mail de OK, guardar en bbdd o contactar con mensajería para preparar un pedido
        file_put_contents(dirname(__FILE__) . '/noti.txt', $DsResponse . "\r\n", FILE_APPEND);
    } else {
        //acciones a realizar si ha sido erroneo
        file_put_contents(dirname(__FILE__) . '/noti.txt', 'PAGO MAL ' . date('d-m-Y m:i:s') . "\r\n", FILE_APPEND);
    }
} catch (\Sermepa\Tpv\TpvException $e) {
    echo $e->getMessage();
}
?>

**Comment by olimpiu6** [comment]
[CODIGO-NOTIFICACION.txt](https://github.com/ssheduardo/sermepa/files/3554108/CODIGO-NOTIFICACION.txt)

**Comment by ssheduardo** [comment]
Una cosa muy simple que puedes hacer es:
En tu archivo noti.php guardar todo lo que te venga a través del $_POST para ver que te esta enviando el banco, con esto descartas si dicho archivo esta siendo llamada o no por el banco y si estas guardando lo que llega por $_POST.

**Comment by olimpiu6** [comment]
Hola de nuevo. Gracias por tu respuesta como siempre. Encontré el fallo, era algo en mi código (una variable de sesión mal formada).  Disculpa la molestia.
