### ISSUE TITLE
Autenticación 3D Secure 2

### ISSUE THREAD

**Issue by MarcSallant** [ssheduardo/sermepa#70]
Hola

Con el nuevo protocolo de autenticación 3DSecure que sale en vigor el 31 de diciembre de 2020, se ve afectada de alguna manera la librería?

**Comment by ssheduardo** [comment]
Aún no lo se la verdad, igualmente necesito un usuario de pruebas FUC para ir probando.

**Comment by ssheduardo** [comment]
Hola,
Lo llegaste a Probar??
