### ISSUE TITLE
Comprobación de pago

### ISSUE THREAD

**Issue by metelidrissi** [ssheduardo/sermepa#76]
Hola,

Siguiendo la documentación:
```
try{
    $redsys = new Sermepa\Tpv\Tpv();
    $key = 'sq7HjrUOBfKmC576ILgskD5srU870gJ7';

    $parameters = $redsys->getMerchantParameters($_POST["Ds_MerchantParameters"]);
    $DsResponse = $parameters["Ds_Response"];
    $DsResponse += 0;
    if ($redsys->check($key, $_POST) && $DsResponse <= 99) {
        //acciones a realizar si es correcto, por ejemplo validar una reserva, mandar un mail de OK, guardar en bbdd o contactar con mensajería para preparar un pedido
    } else {
        //acciones a realizar si ha sido erroneo
    }
} catch (\Sermepa\Tpv\TpvException $e) {
    echo $e->getMessage();
}
```

No recibo ningún $_POST, en el entorno de pruebas, para realizar una acción u otra en función de la respuesta, ¿la recepción de $_POST entiendo que se establece en la creación del botón de pago?

**Comment by metelidrissi** [comment]
Hola @ssheduardo ,

Nada, ya está resuelto, aunque lo tenia en notificación tal y como mencionas en la documentación, en Codeigniter hay que liberar a esa ruta de CSFR en la configuración, sinó, no te permite recibir peticiones POST a esa ruta.

Gracias

**Comment by ssheduardo** [comment]
Perfecto.
