### ISSUE TITLE
Pago con referencia y recurrencia

### ISSUE THREAD

**Issue by metelidrissi** [ssheduardo/sermepa#77]
Hola,

He estado probando y leyendo la documentación de **Redsys** y no me queda claro si es posible hacer pagos recurrentes.

Al probar la librería puedo realizar un pago a 0 y capturar **Ds_Merchant_Identifier** guardando ese dato dentro de la ficha del cliente para más tarde usarlo para otros pagos.

Ese token, me es útil para que pueda realizar otro pago sin tener que introducir de nuevo todos los datos, pero si quisiera adaptar mi plataforma para que cobrara de forma recurrente a ese cliente cada mes (como cualquier sistema de cobros por suscripción), ¿podría ejecutar esa función?

Con el entorno de pruebas no es posible porque aparece esa pantalla de simulación de Redsys el cual si hubiera un proceso Cron ejecutando ese cobro se encontraría con eso...por lo que no pude testearlo.

¿Por otro lado, no sé si quizá esto debería de ser con la API REST de Redsys en vez del Realizar Pago?

Me refiero a que quizá para lo que quiero hacer necesite enviarlo a través de:

https://sis.redsys.es/sis/rest/trataPeticionREST.

Gracias de antemano.

Un saludo

**Comment by ssheduardo** [comment]
En la última versión la 1.4 se implemento el pago recurrente por Rest pasando la referencia que se obtiene por Redirección.

**Comment by josuelmm** [comment]
Siempre me devuelve error 0195 Requiere autenticación SCA
Cuando hago pago recurrente

**Comment by ssheduardo** [comment]
> Siempre me devuelve error 0195 Requiere autenticación SCA Cuando hago pago recurrente

Has hablado con el Banco para ver si te tienen que activar algo?

**Comment by josuelmm** [comment]
Resolvi enviando esto
```
                        $redsys->setParameters([
                            "DS_MERCHANT_EXCEP_SCA"=>"MIT",
                            "DS_MERCHANT_COF_INI"=>"N"
                        ]);
```
