### ISSUE TITLE
DS_MERCHANT_ORDER Error

### ISSUE THREAD

**Issue by darkraul79** [ssheduardo/sermepa#78]
En la funcion SetOrder, compruebas que el número de pedido($order), los 4 primeros caracteres sean numéricos. 
Esto creo que no es un requisito de Redsys, y en mi proyecto genera una excepción, ya que necesito generar número de pedido con caracteres de texto en los primeros caracteres.

Puedes resolverlo??

```

 public function setOrder($order='')
    {
        $order = trim($order);
        if (strlen($order) <= 3 || strlen($order) > 12 || !is_numeric(substr($order, 0, 4))) {
            throw new TpvException('Order id must be a 4 digit string at least, maximum 12 characters.');
        }

        $this->_setParameters['DS_MERCHANT_ORDER'] = $order;

        return $this;
    }

```

He creado una pull request, modificando dos líneas.
Cuando puedas le echas un vistazo.
Gracias.

**Comment by ssheduardo** [comment]
Al final como tuve que subir un nuevo método para el uso de Rest aproveche a quitar la validación de los 4 primeros dígitos y adaptar los test que ya tenía realizado.
Muchas gracias por el PR aunque no lo he usado.
