### ISSUE TITLE
Añadir el campo DS_MERCHANT_EXCEP_SCA para PSD2

### ISSUE THREAD

**Issue by srraul94** [ssheduardo/sermepa#83]
El pago con tarjetas PSD2 necesita el campo DS_MERCHANT_EXCEP_SCA en las peticiones e indicar el tipo de PSD2. Dejo más información aquí. 

https://docsbs.necomplus.net/tpv-virtual/tpv-virtual-redsys/instalaci%C3%B3n/manual-de-integraci%C3%B3n-redirecci%C3%B3n/adaptaciones-psd2/transacciones-iniciadas-por-el-comercio-mit/transacciones-mit-y-uso-de-tokenizaci%C3%B3n-pago-por-referencia/

**Comment by ssheduardo** [comment]
Para estos casos puedes usar el método **setParameters** para que puedas agregar más parámetros de forma dinámica

[https://github.com/ssheduardo/sermepa#m%C3%A9todos-%C3%BAtiles](https://github.com/ssheduardo/sermepa#m%C3%A9todos-%C3%BAtiles)

**Comment by srraul94** [comment]
Genial! entiendo que permite el uso de setParameters y las demás funciones set, según he podido ver en el código. Pensé de primeras que cuando se usaba el setParameters se sustituían los métodos set existentes.
