### ISSUE TITLE
problema con verificacion EMV3DS

### ISSUE THREAD

**Issue by WebSocialManager** [ssheduardo/sermepa#84]
Para poder usar la clase con pagos seguros con autenticacion redsys me dice que tengo que implementar estos 5 pasos intermedios.
https://pagosonline.redsys.es/funcionalidades-autenticacion3DS.html
En ellos les vas enviando los datos de la tarjeta y ellos te responden con las versiones etc.
Solo afecta a REST. con redireccion no es necesario. Me podriais echar una mano para implementar esto?

**Comment by ssheduardo** [comment]
Te aconsejo directamente hablar con Redsys, te lo comento porque las veces que llame a soporte para que envias esos datos de la tarjeta desde tu server te piden mil requisitos, lo más rápido es validar la tarjeta con ellos (por el formulario de redirección) y otra más que es insertando en tu web la validación de tarjeta (ya tienen un script de js para ello) y ya luego con todo eso ya puedes hacer lo cobros, dado que ya tendremos el token y demás datos.

**Comment by WebSocialManager** [comment]
Gracias por la respuesta @ssheduardo 
Ya estoy en comunicacion conRedsys. Estoy usando insite+rest. Asi que ya uso su script para codificar la tarjeta, pero aun asi, me piden que la valide haciendo las peticiones te comento...

Yo por mi lo dejaria con redireccion que es mucho mas comodo. Pero me estan pidiendo implementar insite...

**Comment by ssheduardo** [comment]
En principio con insite es como el de redirección (la diferencia esta en que insite esta dentro).
una vez que ya tienes la validación te darán el token y con la clase puedes hacer los cobros.
Con un amigo usamos el de redirección y luego los cobros por rest.

**Comment by WebSocialManager** [comment]
Voy a volver a plantear el problema a Redsys, A ver si me aclaran algo. Si consigo algo, lo pongo por aqui por si le sirve a alguien. Hay muy poca info sobre insite+rest.
Gracias @ssheduardo

**Comment by ssheduardo** [comment]
Realmente tras hacer el insite, te debe de devolver el token y demás datos con en la redirección y tras eso ya con Rest usando esta clase puedes hacer los cobros sin problema

**Comment by WebSocialManager** [comment]
Buenas @ssheduardo finalmente lo conseguí. Tuve que añadir 1 endpoint que no había en sermepa para poder hacer todo el proceso de autorización. he creado un pull request: https://github.com/ssheduardo/sermepa/pull/85 

He duplicado uno de los endpoint para que la variable de entorno sea mas evidente. Échale un vistazo.

un saludo!

**Comment by ssheduardo** [comment]
Puedes dar un poco más en detalle, lo que te comentaron en el banco, los pasos que tuviste que seguir , las pruebas o un ejemplo.
De esta manera podemos agregar esa info al README para que pueda ayudarle a otros.

**Comment by WebSocialManager** [comment]
Acabo de volver de vacaciones. En cuanto saque un rato lo hago.

**Comment by ssheduardo** [comment]
@WebSocialManager tengo que preguntarte algo, déjame tu contacto cuando puedas.

**Comment by ssheduardo** [comment]
@gorkacano ponte en contacto conmigo, gracias.

**Comment by gorkacano** [comment]
Buenas Eduardo. Que necesitas?

Gorka Cano

________________________________

**Comment by ssheduardo** [comment]
Tienes un email de contacto u otra vía?

**Comment by gorkacano** [comment]
Si. Claro.
***@***.***

Gorka Cano
________________________________
